#theme = "Gruvbox-Dark"

[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.primary]
background = "#000000"
foreground = "#ebdbb2"

[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "0.92"

[font.bold]
family = "Iosevka Nerd Font"
style = "Bold"

[font.italic]
family = "Iosevka Nerd Font"
style = "Bold Italic"

[font.normal]
family = "Iosevka Nerd Font"
style = "Medium"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[terminal.shell]
program = "/bin/bash"

[window]
decorations = "none"
opacity = 0.95

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 12
y = 8

[general]
live_config_reload = true

[terminal]
